steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - nichishi-bot
      - --source=.
      - --region=asia-northeast1
      - --max-instances=1
      - --min-instances=1
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY
