steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - nichishi-bot
      - --source=.
      - --region=asia-northeast1
      - --max-instances=1
      - --min-instances=1
      - --set-secrets=LINE_CHANNEL_SECRET=LINE_CHANNEL_SECRET:latest,LINE_CHANNEL_ACCESS_TOKEN=LINE_CHANNEL_ACCESS_TOKEN:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,MASTER_SPREADSHEET_ID=MASTER_SPREADSHEET_ID:latest,TEMPLATE_SPREADSHEET_ID=TEMPLATE_SPREADSHEET_ID:latest
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY
